### ISSUE TITLE
CT: invalid stroke (CanvasLinePlot)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#23]
Probably related to yesterday's changes to CanvasLinePlot in #16. 

CT is failing with:

```
bamboo : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/bamboo/bamboo_en.html?continuousTest=%7B%22test%22%3A%5B%22bamboo%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610500575059%22%2C%22timestamp%22%3A1610510878325%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid stroke
Error: Assertion failed: invalid stroke
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/assert/js/assert.js:25:13)
at CanvasLinePlot.setStroke (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/bamboo/js/CanvasLinePlot.js:53:15)
at new CanvasLinePlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/bamboo/js/CanvasLinePlot.js:44:10)
at new DemoChartCanvasNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/bamboo/js/demo/DemoChartCanvasNode.js:83:22)
at Object.createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/bamboo/js/demo/BambooDemoScreenView.js:46:63)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/sun/js/demo/DemosScreenView.js:129:26
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/axon/js/Property.js:280:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/axon/js/Property.js:178:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610500575059/axon/js/Property.js:350:32)
id: Bayes Chrome
Snapshot from 1/12/2021, 6:16:15 PM
```

To reproduce manually:

1. Run the bamboo demo 
2. Select "ChartCanvasNode" from the combo box

**Comment by pixelzoom** [comment]
This is being caused by 2 color Properties used in DemoChartCanvasNode:

```js
    const p = new Property( new Color( 128, 128, 128 ) );

    const colors = [ 'red', 'blue', 'green',
      'violet', new Color( 'pink' ), new Property( null ), p
    ];
```

I would have simply removed those Properties, but one of them (`p`) is used in a Emitter listener:

```js
    let time = 0;
    emitter.addListener( dt => {
      time += dt;
      const a = 255 * Math.sin( time * 4 );
      p.set( new Color( a, a / 2, a / 4 ) );
      chartCanvasNode.update();
    } );
```

I wasn't clear on what the intent was here.  So over to the author (@samreid) to address.

**Comment by samreid** [comment]
Fixed and tested locally, closing.
