### ISSUE TITLE
CT: transformed value was not finite

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bamboo#51]
```
bamboo : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/bamboo/bamboo_en.html?continuousTest=%7B%22test%22%3A%5B%22bamboo%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1640030513564%22%2C%22timestamp%22%3A1640032600118%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: transformed value was not finite
Error: Assertion failed: transformed value was not finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/assert/js/assert.js:25:13)
at ChartTransform.modelToView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/ChartTransform.js:82:15)
at ChartTransform.forEachSpacing (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/ChartTransform.js:69:33)
at GridLineSet.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/GridLineSet.js:51:25)
at changedListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/GridLineSet.js:42:40)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Emitter.js:37:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Action.js:195:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Emitter.js:62:19)
at ChartTransform.setYTransform (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/ChartTransform.js:225:27)
id: Bayes Chrome
Snapshot from 12/20/2021, 1:01:53 PM

----------------------------------

bamboo : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/bamboo/bamboo_en.html?continuousTest=%7B%22test%22%3A%5B%22bamboo%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1640030513564%22%2C%22timestamp%22%3A1640037774471%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: transformed value was not finite
Error: Assertion failed: transformed value was not finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/assert/js/assert.js:25:13)
at ChartTransform.modelToView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/ChartTransform.js:82:15)
at ChartTransform.forEachSpacing (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/ChartTransform.js:69:33)
at GridLineSet.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/GridLineSet.js:51:25)
at changedListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/GridLineSet.js:42:40)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Emitter.js:37:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Action.js:195:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Emitter.js:62:19)
at ChartTransform.setYTransform (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/ChartTransform.js:225:27)
id: Bayes Chrome
Snapshot from 12/20/2021, 1:01:53 PM
```

**Comment by pixelzoom** [comment]
This started in CT on 12/19/2021 @ 5:44 PM, and has occurred on every cycle since.  That would seem to coincide with https://github.com/phetsims/bamboo/commit/88efa61830a0124ff7fdc1594e9a7cb7147d3db6 by @samreid on 12/19/2021 @ 4:56 PM.

**Comment by samreid** [comment]
I reproduced this problem by going to "multiple plots" and selecting "log".

**Comment by samreid** [comment]
In the commit https://github.com/phetsims/bamboo/commit/88efa61830a0124ff7fdc1594e9a7cb7147d3db6 2 occurrences of `'loose'` were inadvertently changed to `'lenient'`.  I corrected it in the commit.  Leaving open to check on CT in a column or two.

**Comment by samreid** [comment]
CT looks clear, closing.
